[package]
name = "wiredash-db"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
thiserror.workspace = true
anyhow.workspace = true
rusqlite = { version = "0.32", features = ["bundled-sqlcipher", "column_decltype"] }
tracing.workspace = true
base64 = "0.22"

[dev-dependencies]
tempfile = "3"
