use crate::colors::*;
use crate::{ColorScheme, ThemeDefinition};

pub fn default_light() -> ThemeDefinition {
    ThemeDefinition {
        name: "Workstation Light".into(),
        id: "default-light".into(),
        version: 2.1,
        compatibility_version: 1,
        color_scheme: ColorScheme::Light,
        scopes: ThemeScopes {
            base: ScopeColors {
            primary: ColorVariant {
                    accent: "#E00000".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#505050".into(),
                    background: "#ffffff".into(),
                    border: "#E8E8E8".into(),
                    heading: "#202020".into(),
                    icon: "#505050".into(),
                    separator: "#E8E8E8".into(),
                    placeholder: "#a9a9a9".into(),
                    hover: "#f5f5f5".into(),
                    backdrop: "#0000001a".into(),
                },
            secondary: None,
            disabled: Some(ColorVariant {
                    accent: "#a9a9a9".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#a9a9a9".into(),
                    background: "#f5f5f5".into(),
                    border: "#E8E8E8".into(),
                    heading: "#a9a9a9".into(),
                    icon: "#a9a9a9".into(),
                    separator: "#E8E8E8".into(),
                    placeholder: "#d0d0d0".into(),
                    hover: "#eeeeee".into(),
                    backdrop: "#0000000d".into(),
                }),
            selected: Some(ColorVariant {
                    accent: "#E00000".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#E00000".into(),
                    background: "#fce8e8".into(),
                    border: "#E00000".into(),
                    heading: "#E00000".into(),
                    icon: "#E00000".into(),
                    separator: "#E00000".into(),
                    placeholder: "#a9a9a9".into(),
                    hover: "#f5d0d0".into(),
                    backdrop: "#E000001a".into(),
                }),
            error: Some(ColorVariant {
                    accent: "#E53935".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#E53935".into(),
                    background: "#ffebee".into(),
                    border: "#E53935".into(),
                    heading: "#E53935".into(),
                    icon: "#E53935".into(),
                    separator: "#E53935".into(),
                    placeholder: "#a9a9a9".into(),
                    hover: "#ffcdd2".into(),
                    backdrop: "#E539351a".into(),
                }),
            success: Some(ColorVariant {
                    accent: "#43A047".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#43A047".into(),
                    background: "#E8F5E9".into(),
                    border: "#43A047".into(),
                    heading: "#43A047".into(),
                    icon: "#43A047".into(),
                    separator: "#43A047".into(),
                    placeholder: "#a9a9a9".into(),
                    hover: "#C8E6C9".into(),
                    backdrop: "#43A0471a".into(),
                }),
        },
            navigation_menu: Some(ScopeColors {
            primary: ColorVariant {
                    accent: "#E00000".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#505050".into(),
                    background: "#f8f8f8".into(),
                    border: "#E8E8E8".into(),
                    heading: "#202020".into(),
                    icon: "#707070".into(),
                    separator: "#E8E8E8".into(),
                    placeholder: "#a9a9a9".into(),
                    hover: "#eeeeee".into(),
                    backdrop: "#0000001a".into(),
                },
            secondary: None,
            disabled: None,
            selected: None,
            error: None,
            success: None,
        }),
            editor: None,
            status_bar: None,
            title_bar: None,
            dialog: None,
            context_menu: None,
            list: None,
        },
    }
}

pub fn default_dark() -> ThemeDefinition {
    ThemeDefinition {
        name: "Workstation Dark".into(),
        id: "default-dark".into(),
        version: 2.1,
        compatibility_version: 1,
        color_scheme: ColorScheme::Dark,
        scopes: ThemeScopes {
            base: ScopeColors {
            primary: ColorVariant {
                    accent: "#E00000".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#d4d4d4".into(),
                    background: "#1e1e1e".into(),
                    border: "#3e3e3e".into(),
                    heading: "#e0e0e0".into(),
                    icon: "#a0a0a0".into(),
                    separator: "#3e3e3e".into(),
                    placeholder: "#6e6e6e".into(),
                    hover: "#2a2a2a".into(),
                    backdrop: "#ffffff1a".into(),
                },
            secondary: None,
            disabled: Some(ColorVariant {
                    accent: "#6e6e6e".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#6e6e6e".into(),
                    background: "#2a2a2a".into(),
                    border: "#3e3e3e".into(),
                    heading: "#6e6e6e".into(),
                    icon: "#6e6e6e".into(),
                    separator: "#3e3e3e".into(),
                    placeholder: "#4e4e4e".into(),
                    hover: "#333333".into(),
                    backdrop: "#ffffff0d".into(),
                }),
            selected: Some(ColorVariant {
                    accent: "#E00000".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#ff6b6b".into(),
                    background: "#3a1a1a".into(),
                    border: "#E00000".into(),
                    heading: "#ff6b6b".into(),
                    icon: "#ff6b6b".into(),
                    separator: "#E00000".into(),
                    placeholder: "#6e6e6e".into(),
                    hover: "#4a2020".into(),
                    backdrop: "#E000001a".into(),
                }),
            error: Some(ColorVariant {
                    accent: "#EF5350".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#EF5350".into(),
                    background: "#3a1a1a".into(),
                    border: "#EF5350".into(),
                    heading: "#EF5350".into(),
                    icon: "#EF5350".into(),
                    separator: "#EF5350".into(),
                    placeholder: "#6e6e6e".into(),
                    hover: "#4a2020".into(),
                    backdrop: "#EF53501a".into(),
                }),
            success: Some(ColorVariant {
                    accent: "#66BB6A".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#66BB6A".into(),
                    background: "#1a3a1a".into(),
                    border: "#66BB6A".into(),
                    heading: "#66BB6A".into(),
                    icon: "#66BB6A".into(),
                    separator: "#66BB6A".into(),
                    placeholder: "#6e6e6e".into(),
                    hover: "#204a20".into(),
                    backdrop: "#66BB6A1a".into(),
                }),
        },
            navigation_menu: Some(ScopeColors {
            primary: ColorVariant {
                    accent: "#E00000".into(),
                    accent_foreground: "#ffffff".into(),
                    paragraph: "#c0c0c0".into(),
                    background: "#181818".into(),
                    border: "#3e3e3e".into(),
                    heading: "#e0e0e0".into(),
                    icon: "#909090".into(),
                    separator: "#3e3e3e".into(),
                    placeholder: "#6e6e6e".into(),
                    hover: "#252525".into(),
                    backdrop: "#ffffff1a".into(),
                },
            secondary: None,
            disabled: None,
            selected: None,
            error: None,
            success: None,
        }),
            editor: None,
            status_bar: None,
            title_bar: None,
            dialog: None,
            context_menu: None,
            list: None,
        },
    }
}
